---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_dock: false

# Role: Dotfiles (geerlingguy.dotfiles)
dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .p10k.zsh.local
  - .vimrc
  - .zprofile
  - .zsh-highlighting-overlay.ini
  - .zshrc.local

# Role: Homebrew (geerlingguy.homebrew)
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - automake
  - bat
  - coreutils
  - ffmpeg
  - fzf
  - git
  - gnu-tar
  - htop
  - libtool
  - libuv
  - nvm
  - openjdk
  - pyenv
  - wget
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aegisub
  - atom
  - docker
  - firefox
  - font-meslo-lg-nerd-font
  - font-maven-pro
  - franz
  - google-chrome
  - istat-menus
  - iterm2
  - jdownloader
  - logi-options-plus
  - mkvtoolnix
  - monitorcontrol
  - namechanger
  - notion
  - plex
  - postman
  - skype
  - the-unarchiver
  - transmission
  - transmit
  - visual-studio-code
  - vlc
  - zoom

# Role: Mac App Store CLI (geerlingguy.mas)
mas_signin_dialog: true
mas_email: "Your email"
mas_installed_apps:
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 876111075, name: "Subtitle Extractor" }
  - { id: 975937182, name: "Fantastical - Calendar & Tasks" }


# Role: ZSH (viasite-ansible.zsh)
zsh_antigen_bundles:
  - ansible
  - aws
  - brew
  - docker
  - docker-compose
  - emoji
  - "{{ fzf_widgets }}"
  - git
  - git-extras
  - joshjon/bliss-dircolors
  - macos
  - npm
  - nvm
  - pip
  - poetry
  - python
  - pyenv
  - rsync
  - systemd
  - themes
  - urbainvaes/fzf-marks
  - virtualenv
  - vscode
  - vundle
  - zdharma-continuum/fast-syntax-highlighting
  - zsh-autosuggestions

zsh_aliases:
  - { alias: 'ls', action: 'gls -GFh --color=always' }
  - { alias: 'll', action: 'gls -alF --color=always' }
  - { alias: 'la', action: 'gls -GA --color=always' }
  - { alias: 'grep', action: 'grep --color=always' }
  - { alias: 'fgrep', action: 'fgrep --color=always' }
  - { alias: 'egrep', action: 'egrep --color=always' }
  - { alias: 'doco', action: 'docker-compose' }

zsh_powerlevel10k_instant_prompt: yes

zsh_fzf_path: "$HOME/.fzf/bin"
