---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_dock: false

# Role: Dotfiles (geerlingguy.dotfiles)
dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .vimrc
  - .zshrc

# Role: Homebrew (geerlingguy.homebrew)
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - automake
  - coreutils
  - ffmpeg
  - fzf
  - git
  - gnu-tar
  - htop
  - libtool
  - libuv
  - nvm
  - openjdk
  - pyenv
  - wget
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aegisub
  - atom
  - docker
  - firefox
  - font-meslo-lg-nerd-font
  - font-maven-pro
  - franz
  - google-chrome
  - istat-menus
  - iterm2
  - jdownloader
  - logi-options-plus
  - mkvtoolnix
  - monitorcontrol
  - namechanger
  - notion
  - plex
  - postman
  - skype
  - the-unarchiver
  - transmission
  - transmit
  - visual-studio-code
  - vlc
  - zoom

# Role: Mac App Store CLI (geerlingguy.mas)
mas_signin_dialog: true
mas_email: "Your email"
mas_installed_apps:
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 876111075, name: "Subtitle Extractor" }
  - { id: 975937182, name: "Fantastical - Calendar & Tasks" }

# # Role: OhMyZsh (diodonfrost.ohmyzsh)
# ohmyzsh_theme: agnoster
# ohmyzsh_plugins:
#   - ansible
#   - aws
#   - brew
#   - docker
#   - docker-compose
#   - emoji
#   - git
#   - git-extras
#   - joel-porquet/zsh-dircolors-solarized
#   - macos
#   - npm
#   - nvm
#   - pip
#   - poetry
#   - python
#   - pyenv
#   - rsync
#   - systemd
#   - thefuck
#   - themes
#   - urbainvaes/fzf-marks
#   - virtualenv
#   - vscode
#   - vundle
#   - zdharma/fast-syntax-highlighting
#   - zsh-autosuggestions

# # Role: Powerline10k (diodonfrost.p10k)
# zsh_plugin: ohmyzsh
# p10k_prompt_style: classic
# p10k_prompt_time: 24-hour
# p10k_prompt_separator: angled
# p10k_prompt_head: sharp
# p10k_prompt_tails: flat
# p10k_prompt_height: one-line


# Role: ZSH (viasite-ansible.zsh)
zsh_antigen_bundles:
  - ansible
  - aws
  - brew
  - docker
  - docker-compose
  - emoji
  - git
  - git-extras
  - joel-porquet/zsh-dircolors-solarized
  - macos
  - npm
  - nvm
  - pip
  - poetry
  - python
  - pyenv
  - rsync
  - systemd
  - thefuck
  - themes
  - urbainvaes/fzf-marks
  - virtualenv
  - vscode
  - vundle
  - zdharma/fast-syntax-highlighting
  - zsh-autosuggestions

zsh_aliases: []

zsh_powerlevel9k_left_prompt:
  - os_icon
  - root_indicator
  - dir

zsh_powerlevel9k_right_prompt:
  - status
  - vcs
  - time

zsh_powerlevel_custom_elements: []
zsh_powerlevel9k_shorten_dir_length: 2
zsh_powerlevel9k_vcs_foreground: ~
zsh_powerlevel9k_vcs_clean_background: ~
zsh_powerlevel9k_vcs_modified_background: ~
zsh_powerlevel9k_vcs_untracked_background: ~

zsh_fzf_path: "$HOME/.fzf/bin"
