---
downloads: ~/.ansible-downloads/

configure_dotfiles: true

# Role: Powerline (nass600.powerline)
vundle_user: "{{ ansible_user_id }}"

# Role: Powerline (nass600.powerline)
powerline_config_shell_colorscheme: "blue"
powerline_config_shell_theme: "default_leftonly"
powerline_daemon_destination: "~/.bash_profile"

# Role: Dotfiles (geerlingguy.dotfiles)
dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .bash_aliases
  - .config
  - .gitignore
  - .gitconfig
  - .vimrc
  - .dir_colors

# Role: Homebrew (geerlingguy.homebrew)
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - bash-completion
  - git
  - python
  - automake
  - libtool
  - libuv
  - docker
  - coreutils
  - wget
  - htop
  - mas
  - {name: macvim, install_options: "with-override-system-vim"}

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # Sys
  - totalspaces
  - the-unarchiver
  - java
  - adobe-acrobat-reader
  - flash-player
  - https://raw.githubusercontent.com/caskroom/homebrew-cask/3a68e11fa578e36fe4745d761a6082b0b158391b/Casks/istat-menus.rb
  - transmit
  - renamer
  - calibre
  - lastpass

  # Movies
  - plex-media-player
  - vlc
  - aegisub
  - subsmarine
  - subler
  - mkvtoolnix-app

  # Download
  - transmission
  - jdownloader

  # Design
  - invisionsync

  # Music
  - spotify

  # Communication
  - franz
  - skype

  # Cloud
  - synology-cloud-station-drive

  # Browsers
  - google-chrome
  - firefox

  # Development
  - iterm2
  - virtualbox
  - vagrant
  - docker
  - kitematic

  # IDEs
  - visual-studio-code
  - phpstorm
  - atom
  - macdown

  # Drivers
  - logitech-options

# Role: Mac App Store CLI (geerlingguy.mas)
mas_signin_dialog: true
mas_email: "Your email"
mas_installed_apps:
  - {id: 497799835, name: "Xcode"}
  - {id: 926036361, name: "LastPass Password Manager"}
  - {id: 411643860, name: "DaisyDisk"}
  - {id: 417375580, name: "BetterSnapTool"}
  - {id: 409183694, name: "Keynote"}
  
