---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_dock: false

macos_defaults:
  # Interface
  - { domain: "NSGlobalDomain", key: "AppleInterfaceStyle", type: "string", value: "Dark" } # Dark Interface
  # Dock
  - { domain: "com.apple.dock", key: "autohide", type: "bool", value: "true" } # Autohide
  - { domain: "com.apple.dock", key: "orientation", type: "string", value: "left" } # Position
  - { domain: "com.apple.dock", key: "tilesize", type: "integer", value: "30" } # Tile Size
  - { domain: "com.apple.dock", key: "show-recents", type: "bool", value: "false" } # Hide Recents
  # Users & Groups
  - { domain: "com.apple.loginwindow", key: "GuestEnabled", type: "bool", value: "false" } # Disable guest account
  # Trackpad
  - { domain: "NSGlobalDomain", key: "com.apple.swipescrolldirection", type: "bool", value: "false" } # Scroll direction unnatural
  - { domain: "NSGlobalDomain", key: "com.apple.trackpad.scaling", type: "float", value: "2.5" } # Trackpad speed fast
  # Date & Time
  - { domain: "com.apple.menuextra.clock", key: "DateFormat", type: "string", value: "EEE d MMM HH:mm" } # Show date in clock
  # Finder
  - { domain: "com.apple.finder", key: "ShowExternalHardDrivesOnDesktop", type: "bool", value: "true" }
  - { domain: "com.apple.finder", key: "ShowHardDrivesOnDesktop", type: "bool", value: "false" }
  - { domain: "com.apple.finder", key: "ShowRemovableMediaOnDesktop", type: "bool", value: "true" }
  - { domain: "com.apple.finder", key: "ShowStatusBar", type: "bool", value: "true" }
  - { domain: "com.apple.finder", key: "FXDefaultSearchScope", type: "string", value: "SCcf" } # When performing a search, search the current folder by default
  - { domain: "com.apple.finder", key: "_FXSortFoldersFirst", type: "bool", value: "true" } # Keep folders on top when sorting by name
  - { domain: "com.apple.finder", key: "FXEnableExtensionChangeWarning", type: "bool", value: "false" } # Disable the warning when changing a file extension
  - { domain: "com.apple.finder", key: "NewWindowTarget", type: "string", value: "PfHm" } # New finder window shows home
  # Desktop Services
  - { domain: "com.apple.desktopservices", key: "DSDontWriteNetworkStores", type: "bool", value: "true" } # Avoid creating .DS_Store files on network volumes

# Role: Dotfiles (geerlingguy.dotfiles)
dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .p10k.zsh.local
  - .vimrc
  - .zprofile
  - .zsh-highlighting-overlay.ini
  - .zshrc.local

# Role: Homebrew (geerlingguy.homebrew)
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - automake
  - bat
  - coreutils
  - ffmpeg
  - fzf
  - git
  - gnu-tar
  - htop
  - libtool
  - libuv
  - nvm
  - openjdk
  - pyenv
  - tesseract-lang
  - wget
  - zsh-completions

homebrew_taps:
  - homebrew/core
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - aegisub
  - atom
  - cleanmymac
  - docker
  - firefox
  - font-meslo-lg-nerd-font
  - font-maven-pro
  - franz
  - google-chrome
  - istat-menus
  - iterm2
  - jdownloader
  - logi-options-plus
  - mkvtoolnix
  - monitorcontrol
  - namechanger
  - notion
  - plex
  - postman
  - skype
  - studio-3t
  - the-unarchiver
  - transmission
  - transmit
  - visual-studio-code
  - vlc
  - zoom

# Role: Mac App Store CLI (geerlingguy.mas)
mas_signin_dialog: true
mas_email: "Your email"
mas_installed_apps:
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 876111075, name: "Subtitle Extractor" }
  - { id: 975937182, name: "Fantastical - Calendar & Tasks" }
  - { id: 953040671, name: "hide.me VPN" }


# Role: ZSH (viasite-ansible.zsh)
zsh_antigen_bundles:
  - ansible
  - aws
  - brew
  - docker
  - docker-compose
  - emoji
  - "{{ fzf_widgets }}"
  - git
  - git-extras
  - joshjon/bliss-dircolors
  - macos
  - npm
  - nvm
  - pip
  - poetry
  - python
  - pyenv
  - rsync
  - systemd
  - themes
  - urbainvaes/fzf-marks
  - virtualenv
  - vscode
  - vundle
  # - zdharma-continuum/fast-syntax-highlighting
  - zsh-users/zsh-autosuggestions
  - zsh-users/zsh-syntax-highlighting

zsh_aliases:
  - { alias: 'ls', action: 'gls -GFh --color=always' }
  - { alias: 'll', action: 'gls -alF --color=always' }
  - { alias: 'la', action: 'gls -GA --color=always' }
  - { alias: 'grep', action: 'grep --color=always' }
  - { alias: 'fgrep', action: 'fgrep --color=always' }
  - { alias: 'egrep', action: 'egrep --color=always' }
  - { alias: 'doco', action: 'docker-compose' }

zsh_powerlevel10k_instant_prompt: yes

zsh_fzf_path: "$HOME/.fzf/bin"
