---
downloads: ~/.ansible-downloads/

configure_dotfiles: true

# Role: Dotfiles (geerlingguy.dotfiles)
dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .vimrc
  - .zshrc.local

# Role: Homebrew (geerlingguy.homebrew)
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - bash-completion
  - git
  - automake
  - libtool
  - libuv
  - docker
  - coreutils
  - wget
  - htop
  - mas
  - nvm
  - gnu-tar
  - fzf

homebrew_taps:
  - homebrew/core
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # Sys
  - the-unarchiver
  - adoptopenjdk8 # java
  - adobe-acrobat-reader
  - flash-player
  - https://raw.githubusercontent.com/caskroom/homebrew-cask/3a68e11fa578e36fe4745d761a6082b0b158391b/Casks/istat-menus.rb # istat-menus 5
  - transmit
  - renamer
  - 1password

  # Movies
  - plex
  - vlc
  - aegisub
  # - subsmarine
  - subler
  - mkvtoolnix

  # Download
  - transmission
  - jdownloader

  # Music
  - spotify

  # Communication
  - franz
  - skype

  # Browsers
  - google-chrome
  - firefox

  # Development
  - iterm2
  - docker
  - kitematic

  # IDEs
  - visual-studio-code
  - atom

  # Drivers
  - logitech-options
  - monitorcontrol

  # Fonts
  - font-meslolg-nerd-font
  # - font-maven-pro

  # macOS
  - mysides

# Role: ZSH (viasite-ansible.zsh)
zsh_antigen_bundles:
  - { name: git, command: git }
  - { name: brew, command: brew }
  - { name: docker, command: docker }
  - { name: docker-compose, command: docker-compose }
  - git-extras
  - nvm
  - npm
  - osx
  - joel-porquet/zsh-dircolors-solarized
  - { name: systemd, command: systemctl }
  - { name: zsh-users/zsh-autosuggestions, when: "{{ zsh_version is version_compare('5.0', '>=') }}" }
  - { name: unixorn/autoupdate-antigen.zshplugin, when: "{{ zsh_update_interval > 0 }}" }
  - urbainvaes/fzf-marks # replaces jump plugin, mark, jump and Ctrl+G
  - "{{ fzf_widgets }}"
  - { name: zdharma/fast-syntax-highlighting@v1.2, when: "{{ zsh_version is version_compare('4.3.17', '>=') }}" }

zsh_aliases: []

zsh_powerlevel9k_left_prompt:
  - os_icon
  - root_indicator 
  - dir

zsh_powerlevel9k_right_prompt:
  - status
  - vcs
  - time

zsh_powerlevel_custom_elements: []
zsh_powerlevel9k_shorten_dir_length: 2
zsh_powerlevel9k_vcs_foreground: ~
zsh_powerlevel9k_vcs_clean_background: ~
zsh_powerlevel9k_vcs_modified_background: ~
zsh_powerlevel9k_vcs_untracked_background: ~

zsh_fzf_path: "$HOME/.fzf/bin"

# Role: Mac App Store CLI (geerlingguy.mas)
mas_signin_dialog: true
mas_email: "Your email"
mas_installed_apps:
  - {id: 411643860,  name: "DaisyDisk"}
  - {id: 417375580,  name: "BetterSnapTool"}
  - {id: 876111075,  name: "Subtitle Extractor"}
  - {id: 975937182,  name: "Fantastical - Calendar & Tasks"}
  - {id: 1091189122, name: "Bear"}
  
