---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes

# Role: Powerline (nass600.powerline)
vundle_user: "{{ user }}"

# Role: Powerline (nass600.powerline)
powerline_config_shell_colorscheme: "blue"
powerline_config_shell_theme: "default_leftonly"
powerline_daemon_destination: "~/.bash_profile"

# Role: Dotfiles (geerlingguy.dotfiles)
dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .bash_aliases
  - .config
  - .gitignore
  - .gitconfig
  - .vimrc
  - .dir_colors

# Role: Homebrew (geerlingguy.homebrew)
homebrew_installed_packages:
  - bash-completion
  - git
  - rar
  - python
  - automake
  - libtool
  - libuv
  - docker
  - coreutils
  - wget
  - htop

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # Sys
  - totalspaces
  - the-unarchiver
  - java
  - adobe-reader
  - flash-player
  - istat-menus
  - transmit
  - renamer
  - calibre
  - daisydisk
  - lastpass

  # Movies
  - plex-media-player
  - vlc
  - aegisub
  - subsmarine

  # Download
  - transmission
  - jdownloader

  # Design
  - invisionsync

  # Music
  - spotify

  # Communication
  - franz
  - skype

  # Cloud
  - synology-cloud-station-drive

  # Browsers
  - google-chrome
  - firefox

  # Development
  - iterm2
  - virtualbox
  - vagrant
  - docker
  - kitematic

  # IDEs
  - visual-studio-code
  - phpstorm
  - atom
  - macdown

# Role: Mac App Store CLI (geerlingguy.mas)
mas_installed_apps: []
mas_email: ""
mas_password: ""