---
downloads: ~/.ansible-downloads/

configure_dotfiles: true

# Role: Powerline (nass600.powerline)
vundle_user: "{{ ansible_user_id }}"

# Role: Powerline (nass600.powerline)
powerline_config_shell_colorscheme: "blue"
powerline_config_shell_theme: "default_leftonly"
powerline_daemon_destination: "~/.bash_profile"

# Role: Dotfiles (geerlingguy.dotfiles)
dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .bash_aliases
  - .config
  - .gitignore
  - .gitconfig
  - .vimrc
  - .dir_colors

# Role: Homebrew (geerlingguy.homebrew)
homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - bash-completion
  - git
  - automake
  - libtool
  - libuv
  - docker
  - coreutils
  - wget
  - htop
  - mas
  - nvm

homebrew_taps:
  - homebrew/core
  - homebrew/cask-drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # Sys
  - the-unarchiver
  - java
  - adobe-acrobat-reader
  - flash-player
  - https://raw.githubusercontent.com/caskroom/homebrew-cask/3a68e11fa578e36fe4745d761a6082b0b158391b/Casks/istat-menus.rb
  - transmit
  - renamer
  - 1password

  # Movies
  - plex
  - vlc
  - aegisub
  - subsmarine
  - subler
  - mkvtoolnix

  # Download
  - transmission
  - jdownloader

  # Music
  - spotify

  # Communication
  - franz
  - skype

  # Browsers
  - google-chrome
  - firefox

  # Development
  - iterm2
  - docker
  - kitematic

  # IDEs
  - visual-studio-code
  - atom

  # Drivers
  - logitech-options
  - monitorcontrol

# Role: Mac App Store CLI (geerlingguy.mas)
mas_signin_dialog: true
mas_email: "Your email"
mas_installed_apps:
  - {id: 411643860, name: "DaisyDisk"}
  - {id: 417375580, name: "BetterSnapTool"}
  - {id: 876111075, name: "Subtitle Extractor"}
  - {id: 975937182, name: "Fantastical - Calendar & Tasks"}
  
