---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  tasks:
    - name: Set macOS default settings
      community.general.osx_defaults:
        domain: "{{ item['domain'] }}"
        key: "{{ item['key'] }}"
        type: "{{ item['type'] | default(omit) }}"
        value: "{{ item['value'] }}"
      loop: "{{ macos_defaults }}"

  roles:
    - role: geerlingguy.mac.homebrew
      ignore_errors: true
    - role: geerlingguy.mac.mas
      ignore_errors: true
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: nass600.vundle
      when: configure_dotfiles
      ignore_errors: true
    - role: viasite-ansible.zsh
      when: configure_dotfiles
