---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']
    - name: Configure macOS settings
      shell: "bin/osx-settings"
      changed_when: false
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['apps', 'brew', 'skip_ansible_lint']
      ignore_errors: true
    - role: geerlingguy.mas
      when: mas_installed_apps
      ignore_errors: true
      tags: ['apps', 'mas', 'skip_ansible_lint']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles', 'skip_ansible_lint']
    # - role: nass600.powerline
    #   when: configure_dotfiles
    #   tags: ['dotfiles', 'skip_ansible_lint']
    # - role: nass600.vundle
    #   when: configure_dotfiles
    #   tags: ['dotfiles', 'skip_ansible_lint']
