---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  # post_tasks:
  #   - name: Configure macOS settings
  #     shell: "bin/macos-settings"
  #     changed_when: false

  roles:
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: nass600.vundle
      when: configure_dotfiles
    - role: diodonfrost.ohmyzsh
    - role: diodonfrost.p10k
    # - role: viasite-ansible.zsh
    #   when: configure_dotfiles
