---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: nass600.vundle
  - name: viasite-ansible.zsh
    src: https://github.com/nass600/ansible-role-zsh

collections:
  - name: geerlingguy.mac
